# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: 
title: Personal Page
author: ABHISHEK 
description: Personal blog and resume
avatar: profile.png
email: abhishek22596@gmail.com
github: nadgeri14 # username
twitter: nadgeri_abhi
linkedin: abhishek-nadgeri-a7546456
stackoverflow: null   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: Abhishek_4998
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
